title: The Basics of Forensics/IR in a Gsuite Environment
speaker:
    - name: Jeff Bryner
      job_title: CISO
      twitter: "@0x7eff"
      bio: >-
        Jeff is the CISO at Vacasa and has been doing security for 30 years with a focus on forensics and incident response.
company: Vacasa
time: 1:05pm-1:35pm
abstract: >-
    The Basics of Forensics/IR in a Gsuite Environment.