title: The Basics of Forensics/IR in a Gsuite Environment
speaker: Jeff Bryner
twitter: "@0x7eff"
bio: >-
    Jeff is the CISO at Vacasa and has been doing security for 30 years with a focus on forensics and incident response.
job_title: CISO
company: Vacasa
time: TBD
abstract: >-
    The Basics of Forensics/IR in a Gsuite Environment.